### ISSUE TITLE
loxone_ws does not survive Miniserver restart

### ISSUE THREAD

**Issue by axxelG** [XciD/loxone-ws#8]
```
WARN[2019-10-13T17:44:27+01:00] Miniserver out of service!
WARN[2019-10-13T17:44:27+01:00] Disconnected, reconnecting
WARN[2019-10-13T17:44:57+01:00] Error during reconnection, retrying
WARN[2019-10-13T17:44:57+01:00] Disconnected, reconnecting
INFO[2019-10-13T17:45:27+01:00] Asking for Public Key
INFO[2019-10-13T17:45:27+01:00] Starting websocket pump
INFO[2019-10-13T17:45:27+01:00] Public Key OK
INFO[2019-10-13T17:45:27+01:00] Key Exchange with Miniserver
INFO[2019-10-13T17:45:27+01:00] Key Exchange OK
INFO[2019-10-13T17:45:27+01:00] Authentication Starting
INFO[2019-10-13T17:45:27+01:00] Authentication OK
WARN[2019-10-13T17:45:27+01:00] Disconnected, reconnecting
INFO[2019-10-13T17:45:27+01:00] error: websocket: close 1005 (no status)
INFO[2019-10-13T17:45:27+01:00] Stopping pump
INFO[2019-10-13T17:45:57+01:00] Asking for Public Key
INFO[2019-10-13T17:45:57+01:00] Starting websocket pump
INFO[2019-10-13T17:45:57+01:00] Public Key OK
INFO[2019-10-13T17:45:57+01:00] Key Exchange with Miniserver
WARN[2019-10-13T17:45:57+01:00] Disconnected, reconnecting
INFO[2019-10-13T17:45:57+01:00] Stopping pump
INFO[2019-10-13T17:46:27+01:00] Asking for Public Key
INFO[2019-10-13T17:46:27+01:00] Starting websocket pump
INFO[2019-10-13T17:46:27+01:00] Public Key OK
INFO[2019-10-13T17:46:27+01:00] Key Exchange with Miniserver
INFO[2019-10-13T17:46:28+01:00] Key Exchange OK
INFO[2019-10-13T17:46:28+01:00] Authentication Starting
WARN[2019-10-13T17:46:28+01:00] Error during reconnection, retrying
WARN[2019-10-13T17:46:28+01:00] Disconnected, reconnecting
INFO[2019-10-13T17:46:58+01:00] Starting websocket pump
INFO[2019-10-13T17:46:58+01:00] Asking for Public Key
INFO[2019-10-13T17:46:58+01:00] Public Key OK
INFO[2019-10-13T17:46:58+01:00] Key Exchange with Miniserver
INFO[2019-10-13T17:46:58+01:00] Stopping disconnect loop
panic: runtime error: index out of range [-1]

goroutine 583 [running]:
github.com/XciD/loxone_ws/crypto.unpad(0x1954b40, 0x0, 0x108, 0x10, 0x1954b40, 0x0, 0x108, 0x0, 0x0)
        <XXX>/go/src/github.com/XciD/loxone_ws/crypto/crypto.go:108 +0x130
github.com/XciD/loxone_ws/crypto.DecryptAES(0x198a000, 0x161, 0x191cac0, 0x40, 0x1c1c1e0, 0x20, 0x60, 0x0, 0x0, 0x8, ...)
        <XXX>/go/src/github.com/XciD/loxone_ws/crypto/crypto.go:99 +0x1f8
github.com/XciD/loxone_ws.(*encrypt).decryptCmd(...)
        <XXX>/go/src/github.com/XciD/loxone_ws/loxone.go:610
github.com/XciD/loxone_ws.(*Loxone).sendCmdWithEnc(0x18c8ac0, 0x1c1c360, 0x1b, 0x2, 0x3b6b30, 0x1f18080, 0x1b, 0x0, 0x0)
        <XXX>/go/src/github.com/XciD/loxone_ws/loxone.go:330 +0x3dc
github.com/XciD/loxone_ws.(*Loxone).createToken(0x18c8ac0, 0x7ef897f1, 0xa, 0x7ef89806, 0x1e, 0x191cac0, 0x40, 0x0, 0x0)
        <XXX>/go/src/github.com/XciD/loxone_ws/loxone.go:441 +0xc0
github.com/XciD/loxone_ws.(*Loxone).authenticate(0x18c8ac0, 0x0, 0x0)
        <XXX>/go/src/github.com/XciD/loxone_ws/loxone.go:426 +0x554
github.com/XciD/loxone_ws.(*Loxone).connect(0x18c8ac0, 0x6, 0x1944fac)
        <XXX>/go/src/github.com/XciD/loxone_ws/loxone.go:209 +0x38
github.com/XciD/loxone_ws.(*Loxone).handleReconnect(0x18c8ac0)
        <XXX>/go/src/github.com/XciD/loxone_ws/loxone.go:236 +0x160
created by github.com/XciD/loxone_ws.(*Loxone).connect
        <XXX>/go/src/github.com/XciD/loxone_ws/loxone.go:216 +0x70
```

I'm using a version with the latest commits from master in loxone_ws and loxone-prometheus-exporter.
@XciD: Looking at your last commits, I guess you are currently working on the websocket connection. For me this issue is not important at the moment but will be a show stopper later.

**Comment by XciD** [comment]
Should be ok now.
